name: Release

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    strategy:
      matrix:
        version:
          - branch: "1.18.2"
            minecraft: "1.18.2"
            loader: "Forge"
            java: 17

          - branch: "1.19.2"
            minecraft: "1.19.2"
            loader: "Forge"
            java: 17

          - branch: "1.20.1"
            minecraft: "1.20.1"
            loader: "Forge-NeoForge"
            java: 17

          - branch: "port-1.21.1-neoforge"
            minecraft: "1.21.1"
            loader: "NeoForge"
            java: 21

          - branch: "port-1.21.1-forge"
            minecraft: "1.21.1"
            loader: "Forge"
            java: 21

    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ matrix.version.branch }}

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.version.java }}
          cache: gradle

      - name: Setup gradle
        run: chmod +x gradlew

      - name: Build ${{ matrix.version.branch }}
        continue-on-error: true
        run: ./gradlew build --no-daemon

      - name: Upload mod jar
        uses: actions/upload-artifact@v4
        with:
          name: buildersdelight-${{ matrix.version.minecraft }}-${{ matrix.version.loader }}
          path: build/libs/*.jar

  create-tag:
    if: |
      github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      tag: ${{ steps.version.outputs.tag }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Detect version
        id: version
        shell: bash
        run: |
          VERSION=$(grep -E '^## [0-9]+\.[0-9]+\.[0-9]+' CHANGES.md \
            | head -1 \
            | sed -E 's/^## //')

          if [ -z "$VERSION" ]; then
            echo "No version found in CHANGES.md"
            exit 1
          fi

          TAG="v$VERSION"

          echo "Detected version: $TAG"

          if git tag --list | grep -qx "$TAG"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

          echo "tag=$TAG" >> $GITHUB_OUTPUT


      - name: Create tag
        if: steps.version.outputs.exists != 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag ${{ steps.version.outputs.tag }}
          git push origin ${{ steps.version.outputs.tag }}


  check-release:
    needs: build
    if: github.event_name == 'push' && !(github.ref == format('refs/heads/{0}', github.event.repository.default_branch))
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check new changelog version
        id: changelog
        shell: bash
        run: |
            if [ ! -f CHANGES.md ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            exit 0
            fi

            VERSION=$(grep '^## v' CHANGES.md | head -1 | sed 's/## //' || true)

            if [ -z "$VERSION" ]; then
            echo "No version found in CHANGES.md"
            echo "exists=true" >> $GITHUB_OUTPUT
            exit 0
            fi

            echo "Detected version: $VERSION"

            if git tag | grep -q "^$VERSION$"; then
            echo "exists=true" >> $GITHUB_OUTPUT
            else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            fi


      - name: Create PR
        if: steps.changelog.outputs.exists == 'false'
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Release ${{ steps.changelog.outputs.version }}"
          draft: true
          body: |
            Automated release PR.

            Version:
            ${{ steps.changelog.outputs.version }}

            Changelog:
            ```md
            $(awk '/^## ${{ steps.changelog.outputs.version }}/,/^## /' CHANGES.md)
            ```

          branch: release/${{ steps.changelog.outputs.version }}
          base: ${{ github.event.repository.default_branch }}


  release:
    needs: [build, create-tag]
    if: needs.create-tag.outputs.tag != ''
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download built jars
        uses: actions/download-artifact@v4
        with:
          path: release-jars
          merge-multiple: true


      - name: Generate release notes
        shell: bash
        run: |
          TAG=${{ needs.create-tag.outputs.tag }}
          VERSION=${TAG#v}

          echo "Changes" > RELEASE.md
          echo "" >> RELEASE.md

          awk -v version="$VERSION" '
          $0 ~ "^## "version"$" {flag=1; next}
          /^## / && flag {exit}
          flag {print}
          ' CHANGES.md > RELEASE.md

          cat RELEASE.md

    
      - name: Get release name
        id: release_name
        run: |
          echo "name=${{ needs.create-tag.outputs.tag }}" | sed 's/^v//' | xargs -I{} echo "{} Release" >> $GITHUB_OUTPUT

      - name: Check releases
        run: |
          if ! find release-jars -name "*.jar" | grep -q .; then
            echo "No jars built"
            exit 1
          fi

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.create-tag.outputs.tag }}
          name: ${{ steps.release_name.outputs.name }}
          draft: true
          body_path: RELEASE.md
          files: |
            release-jars/**/*.jar